### ISSUE TITLE
Save Ink :: throwing exception 'Access to path denied' when trying to save.

### ISSUE THREAD

**Issue by zanepartain** [ZanePartain/SightSign#4]
**Expected:** user should be able to save the in kin a location where we won't run into access denied exceptions.

**Actual:** The ink is being saved to a location where we do not have permission to write to.

**Reproduce:**
1.  Have ink on screen
2.  Edit > Save

**Comment by zanepartain** [comment]
@brcamp13 It saves the files as a directory! Instead of a file. This might be the reason why we are getting a permission denied.

**Comment by zanepartain** [comment]
verified fixed, no need to call Create_SaveFile_Directory() every with the complete filename. We changed it, and seems to work perfectly!

**Comment by brcamp13** [comment]
Okay, thanks for catching that!
